//
// ExpenseByCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExpenseByCategory: Codable, JSONEncodable, Hashable {

    public var housing: [Expense]
    public var food: [Expense]
    public var transport: [Expense]
    public var other: [Expense]
    public var savings: [Expense]
    public var debt: [Expense]

    public init(housing: [Expense], food: [Expense], transport: [Expense], other: [Expense], savings: [Expense], debt: [Expense]) {
        self.housing = housing
        self.food = food
        self.transport = transport
        self.other = other
        self.savings = savings
        self.debt = debt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case housing
        case food
        case transport
        case other
        case savings
        case debt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(housing, forKey: .housing)
        try container.encode(food, forKey: .food)
        try container.encode(transport, forKey: .transport)
        try container.encode(other, forKey: .other)
        try container.encode(savings, forKey: .savings)
        try container.encode(debt, forKey: .debt)
    }
}

