//
// Expense.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Expense: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var cost: Double
    public var category: String

    public init(id: String, name: String, cost: Double, category: String) {
        self.id = id
        self.name = name
        self.cost = cost
        self.category = category
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case cost
        case category
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(cost, forKey: .cost)
        try container.encode(category, forKey: .category)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Expense: Identifiable {}
