server:
  port: 8080
  address: 0.0.0.0

spring: 
  datasource:
    url: jdbc:sqlite:/var/local.db 
    driver-class-name: org.sqlite.JDBC

sql: 
  init:
    mode: always

springdoc:
  api-docs: 
    enabled: true
    path: /swagger.json
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    show-actuator: true
